### ISSUE TITLE
Constructor error thrown when trying to include a partial

### ISSUE THREAD

**Issue by gesa** [treygriffith/metalsmith-include#1]
Seems no matter what I do I can't get this to work. I get the same error when running metalsmith via cli or grunt:

```
/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:176
          throw new exports.ConstructorError('while constructing a mapping', n
                ^
while constructing a mapping
  in "undefined", line 1, column 9
found unhashable key
  in "undefined", line 1, column 10
    at ConstructorError.YAMLError (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:72:46)
    at ConstructorError.MarkedYAMLError (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/errors.js:88:45)
    at new ConstructorError (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:17:53)
    at Constructor.BaseConstructor.BaseConstructor.construct_mapping (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:176:17)
    at Constructor.Constructor.construct_mapping (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:306:54)
    at /usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:548:23
    at Constructor.BaseConstructor.BaseConstructor.construct_document (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:90:41)
    at Constructor.BaseConstructor.BaseConstructor.get_single_data (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/constructor.js:80:21)
    at load (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/node_modules/yaml-js/lib/yaml.js:113:19)
    at parse (/usr/local/lib/node_modules/metalsmith/node_modules/front-matter/index.js:26:27)
```

I've triple checked my front matter matches yours, but no dice. Any suggestions?

**Comment by Endorel** [comment]
apparently it only works if the partial is in the same directory as the sourcefile. Or have you solved this issue? If so, I would greatly appreciate it if you could post the solution.

**Comment by gesa** [comment]
@Endorel if I recall, I gave up and invented a workaround. It's been a minute…

**Comment by doublejosh** [comment]
Yeah, this plugin appears to only check the `/src` directory. #8
