### ISSUE TITLE
Error: Unknown file thanks.md

### ISSUE THREAD

**Issue by jonathangarner** [treygriffith/metalsmith-include#2]
I am very new to using node & static site generators, so I'm quite sure I'm just doing this wrong.
I have spent a long time trying to fix this before posting here

Following the simple example from your readme file I cannot get it to compile without throwing an error. 

The issue seems to occur from the include line in the YAML of the index.md file:
    ---
title: Home
template: home.hbt
include:
  thanks: thanks.md
    ---

here is the full error message from the terminal:

    Users/Jonathan/Sites/metalsmith/index.js:13
        if (err) { throw err; }
                         ^
    Error: Unknown file thanks.md
    at include (/Users/Jonathan/node_modules/metalsmith-include/index.js:54:45)
    at /Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:39:24)
    at async.each (/Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:117:9)
    at convert (/Users/Jonathan/node_modules/metalsmith-include/index.js:42:7)
    at /Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:118:13
    at Array.forEach (native)
    at _each (/Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:39:24)
    at async.each (/Users/Jonathan/node_modules/metalsmith-include/node_modules/async/lib/async.js:117:9)

Also to mention I am using handlebars instead of jade (although I don't believe this is an issue), and the code in the home.hbt file is as follows:

    <div class="main-wrapper">
        {{{ contents }}}
    </div>

    <div>
    {{{ thanks }}}
    </div>

Any help would be much appreciated!

**Comment by treygriffith** [comment]
Closing this due to inactivity.
